#!/usr/bin/env python3
"""
Wrapper for options_backtester_v2_3_3_5.py to accept JSON config from web interface
"""

import sys
import json
import os
from datetime import datetime

# Import the backtester functions
from options_backtester_v2_3_3_5 import *

def load_config_from_json(json_path):
    """Load configuration from JSON file generated by web interface"""
    with open(json_path, 'r') as f:
        web_config = json.load(f)
    
    # Convert web config format to script config format
    config = {
        'backtest_name': web_config.get('backtest_name') or web_config.get('backtestName', ''),
        'symbol': web_config.get('symbol', 'SPX'),
        'start_date': web_config.get('start_date') or web_config.get('startDate', ''),
        'end_date': web_config.get('end_date') or web_config.get('endDate', ''),
        'entry_time': web_config.get('entry_time') or web_config.get('entryTime', '10:00'),
        'dte': web_config.get('dte', 0),
        'strategy': web_config.get('strategy', ''),
        'legs': web_config.get('legs', []),
        'detection_bar_size': web_config.get('detection_bar_size') or web_config.get('detectionBarSize', 1),
        'ten_second_data': web_config.get('ten_second_data') if web_config.get('ten_second_data') is not None else web_config.get('tenSecondData', False),
        'concurrent_trades': web_config.get('concurrent_trades') if web_config.get('concurrent_trades') is not None else web_config.get('concurrentTrades', False),
        'avoid_pdt': web_config.get('avoid_pdt') if web_config.get('avoid_pdt') is not None else web_config.get('avoidPdt', False),
        'allow_synthetic': web_config.get('allow_synthetic') if web_config.get('allow_synthetic') is not None else web_config.get('allowSynthetic', True),
        'starting_capital': web_config.get('starting_capital') or web_config.get('startingCapital', 100000),
        'allocation_type': web_config.get('allocation_type') or web_config.get('allocationType', 'pct'),
        'allocation_value': web_config.get('allocation_value') or web_config.get('allocationValue', 10),
        # Net premium filter (optional)
        'net_premium_min': web_config.get('net_premium_min') or web_config.get('netPremiumMin'),
        'net_premium_max': web_config.get('net_premium_max') or web_config.get('netPremiumMax'),
        'expiry_close_time': web_config.get('expiry_close_time') or web_config.get('expiryCloseTime', '16:15')
    }
    
    # Handle take profit
    tp_pct = web_config.get('take_profit_pct') if web_config.get('take_profit_pct') is not None else web_config.get('takeProfitPct')
    tp_dollar = web_config.get('take_profit_dollar') if web_config.get('take_profit_dollar') is not None else web_config.get('takeProfitDollar')
    if tp_pct is not None and str(tp_pct).strip() != '':
        config['take_profit_pct'] = tp_pct
        config['take_profit_dollar'] = None
    else:
        config['take_profit_pct'] = None
        config['take_profit_dollar'] = tp_dollar
    
    # Handle stop loss
    sl_pct = web_config.get('stop_loss_pct') if web_config.get('stop_loss_pct') is not None else web_config.get('stopLossPct')
    sl_dollar = web_config.get('stop_loss_dollar') if web_config.get('stop_loss_dollar') is not None else web_config.get('stopLossDollar')
    if sl_pct is not None and str(sl_pct).strip() != '':
        config['stop_loss_pct'] = sl_pct
        config['stop_loss_dollar'] = None
    else:
        config['stop_loss_pct'] = None
        config['stop_loss_dollar'] = sl_dollar
    
    # Handle wing configuration if present
    if 'wing_config' in web_config:
        config['wing_config'] = web_config['wing_config']
    
    # Handle entry time range (optional end time)
    entry_time_max = web_config.get('entry_time_max') or web_config.get('entryTimeMax', '')
    if entry_time_max:
        config['entry_time_max'] = entry_time_max
    
    # Handle entry conditions (preset or custom)
    options_entry_type = web_config.get('options_entry_type') or web_config.get('optionsEntryType', 'none')
    config['options_entry_type'] = options_entry_type
    
    if options_entry_type == 'preset':
        config['preset_condition'] = web_config.get('preset_condition') or web_config.get('presetCondition', '1')
        config['preset_operator'] = web_config.get('preset_operator') or web_config.get('presetOperator', '>')
        config['preset_threshold'] = float(web_config.get('preset_threshold') or web_config.get('presetThreshold', 0))
        if config['preset_condition'] == '5':
            config['velocity_lookback'] = int(web_config.get('velocity_lookback') or web_config.get('velocityLookback', 5))
    elif options_entry_type == 'custom':
        price_conds = web_config.get('price_conditions') or web_config.get('priceConditions', [])
        if price_conds:
            config['price_conditions'] = price_conds
    else:
        price_conds = web_config.get('price_conditions') or web_config.get('priceConditions', [])
        if price_conds:
            config['price_conditions'] = price_conds
    
    # Handle exit conditions (signal-based, optional)
    options_exit_type = web_config.get('options_exit_cond_type', 'preset')
    config['options_exit_cond_type'] = options_exit_type
    
    if options_exit_type == 'preset' and web_config.get('exit_preset_condition'):
        config['exit_preset_condition'] = web_config['exit_preset_condition']
        config['exit_preset_operator'] = web_config.get('exit_preset_operator', '>')
        try:
            config['exit_preset_threshold'] = float(web_config.get('exit_preset_threshold') or 0)
        except (ValueError, TypeError):
            config['exit_preset_threshold'] = 0
        if web_config.get('exit_preset_condition') == '5':
            try:
                config['exit_velocity_lookback'] = int(web_config.get('exit_velocity_lookback') or 5)
            except (ValueError, TypeError):
                config['exit_velocity_lookback'] = 5
    elif options_exit_type == 'custom':
        config['exit_price_conditions'] = web_config.get('exit_price_conditions', [])
    
    if 'iv_entry_condition' in web_config and web_config['iv_entry_condition']:
        config['iv_entry_condition'] = web_config['iv_entry_condition']
    
    eod_action = web_config.get('eod_action') or web_config.get('eodAction', 'close')
    if eod_action:
        config['eod_action'] = eod_action
    
    trade_frequency = web_config.get('trade_frequency') or web_config.get('tradeFrequency', 'daily')
    if trade_frequency:
        config['trade_frequency'] = trade_frequency
    
    entry_days = web_config.get('entry_days') or web_config.get('entryDays', [])
    if entry_days:
        config['entry_days'] = entry_days
    
    allow_skewed = web_config.get('allow_skewed_wings') or web_config.get('allowSkewedWings', False)
    if allow_skewed:
        config['allow_skewed_wings'] = allow_skewed
    
    return config

def main():
    """Main entry point for web-based backtesting"""
    
    if len(sys.argv) < 3 or sys.argv[1] != '--config':
        print("Usage: python3 backtest_wrapper.py --config <config.json> [--id <backtest_id>]")
        sys.exit(1)
    
    config_path = sys.argv[2]
    
    # Parse optional --id parameter
    backtest_id = None
    if len(sys.argv) >= 5 and sys.argv[3] == '--id':
        backtest_id = sys.argv[4]
    
    if not os.path.exists(config_path):
        print(f"Config file not found: {config_path}")
        sys.exit(1)
    
    try:
        # Load config from JSON
        config = load_config_from_json(config_path)
        
        # Get API key from environment
        api_key = os.environ.get('POLYGON_API_KEY')
        if not api_key:
            print("ERROR: POLYGON_API_KEY environment variable not set")
            sys.exit(1)
        
        # Create REST client (30s per-request timeout so a stalled Polygon call
        # cannot hang the entire backtest subprocess indefinitely)
        client = RESTClient(api_key, connect_timeout=10, read_timeout=30)
        
        # Run backtest
        print(f"\n{'='*80}")
        print(f"{'OPTIONS BACKTESTING SYSTEM':^80}")
        print(f"{'='*80}")
        print(f"\nSymbol: {config['symbol']}")
        print(f"Strategy: {config['strategy']}")
        print(f"Period: {config['start_date']} to {config['end_date']}")
        print(f"Starting Capital: ${config['starting_capital']:,.2f}")
        print(f"\nRunning backtest...")
        print(f"{'='*80}\n")
        
        trades, equity, decision_log = run_backtest(config, client)
        
        # Save results with backtest_id suffix if provided
        plot_results(equity, config, backtest_id=backtest_id)
        calculate_stats(trades, config)
        save_trade_log(trades, backtest_id=backtest_id)
        
        # Save decision log as JSON (always write, even if empty)
        output_dir = 'backtest_results'
        os.makedirs(output_dir, exist_ok=True)
        dl_suffix = f'_{backtest_id}' if backtest_id else ''
        dl_path = os.path.join(output_dir, f'decision_log{dl_suffix}.json')
        with open(dl_path, 'w') as f:
            json.dump(decision_log if decision_log else [], f)
        print(f"  Decision log saved: {dl_path} ({len(decision_log) if decision_log else 0} days)")
        
        print(f"\n{'='*80}")
        print("BACKTEST COMPLETE")
        print(f"{'='*80}\n")
        
    except KeyboardInterrupt:
        print("\n\nBacktest interrupted by user.")
        sys.exit(1)
    except Exception as e:
        print(f"\n\nERROR: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)

if __name__ == "__main__":
    main()
