#!/usr/bin/env python3
"""
Wrapper for options_backtester_v2_3_3_5.py to accept JSON config from web interface
"""

import sys
import json
import os
from datetime import datetime

# Import the backtester functions
from options_backtester_v2_3_3_5 import *

def load_config_from_json(json_path):
    """Load configuration from JSON file generated by web interface"""
    with open(json_path, 'r') as f:
        web_config = json.load(f)
    
    # Convert web config format to script config format
    config = {
        'backtest_name': web_config.get('backtest_name', ''),
        'symbol': web_config['symbol'],
        'start_date': web_config['start_date'],
        'end_date': web_config['end_date'],
        'entry_time': web_config['entry_time'],
        'dte': web_config['dte'],
        'strategy': web_config['strategy'],
        'legs': web_config['legs'],
        'detection_bar_size': web_config['detection_bar_size'],
        'concurrent_trades': web_config['concurrent_trades'],
        'avoid_pdt': web_config['avoid_pdt'],
        'starting_capital': web_config['starting_capital'],
        'allocation_type': web_config['allocation_type'],
        'allocation_value': web_config['allocation_value'],
        # Net premium filter (optional)
        'net_premium_min': web_config.get('net_premium_min'),
        'net_premium_max': web_config.get('net_premium_max')
    }
    
    # Handle take profit
    if web_config.get('take_profit_pct') is not None:
        config['take_profit_pct'] = web_config['take_profit_pct']
        config['take_profit_dollar'] = None
    else:
        config['take_profit_pct'] = None
        config['take_profit_dollar'] = web_config.get('take_profit_dollar')
    
    # Handle stop loss
    if web_config.get('stop_loss_pct') is not None:
        config['stop_loss_pct'] = web_config['stop_loss_pct']
        config['stop_loss_dollar'] = None
    else:
        config['stop_loss_pct'] = None
        config['stop_loss_dollar'] = web_config.get('stop_loss_dollar')
    
    # Handle wing configuration if present
    if 'wing_config' in web_config:
        config['wing_config'] = web_config['wing_config']
    
    # Handle entry time range (optional end time)
    if 'entry_time_max' in web_config and web_config['entry_time_max']:
        config['entry_time_max'] = web_config['entry_time_max']
    
    # Handle price conditions (optional)
    if 'price_conditions' in web_config and web_config['price_conditions']:
        config['price_conditions'] = web_config['price_conditions']
    
    return config

def main():
    """Main entry point for web-based backtesting"""
    
    if len(sys.argv) < 3 or sys.argv[1] != '--config':
        print("Usage: python3 backtest_wrapper.py --config <config.json> [--id <backtest_id>]")
        sys.exit(1)
    
    config_path = sys.argv[2]
    
    # Parse optional --id parameter
    backtest_id = None
    if len(sys.argv) >= 5 and sys.argv[3] == '--id':
        backtest_id = sys.argv[4]
    
    if not os.path.exists(config_path):
        print(f"Config file not found: {config_path}")
        sys.exit(1)
    
    try:
        # Load config from JSON
        config = load_config_from_json(config_path)
        
        # Get API key from environment
        api_key = os.environ.get('POLYGON_API_KEY')
        if not api_key:
            print("ERROR: POLYGON_API_KEY environment variable not set")
            sys.exit(1)
        
        # Create REST client
        client = RESTClient(api_key)
        
        # Run backtest
        print(f"\n{'='*80}")
        print(f"{'OPTIONS BACKTESTING SYSTEM':^80}")
        print(f"{'='*80}")
        print(f"\nSymbol: {config['symbol']}")
        print(f"Strategy: {config['strategy']}")
        print(f"Period: {config['start_date']} to {config['end_date']}")
        print(f"Starting Capital: ${config['starting_capital']:,.2f}")
        print(f"\nRunning backtest...")
        print(f"{'='*80}\n")
        
        trades, equity = run_backtest(config, client)
        
        # Save results with backtest_id suffix if provided
        plot_results(equity, config, backtest_id=backtest_id)
        calculate_stats(trades, config)
        save_trade_log(trades, backtest_id=backtest_id)
        
        print(f"\n{'='*80}")
        print("BACKTEST COMPLETE")
        print(f"{'='*80}\n")
        
    except KeyboardInterrupt:
        print("\n\nBacktest interrupted by user.")
        sys.exit(1)
    except Exception as e:
        print(f"\n\nERROR: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)

if __name__ == "__main__":
    main()
